environment:
  build_version: 6.3.0
  Version: $(build_version)
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
 - cmd: nuget restore Grace.MVC.sln
build:
  project: Grace.MVC.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- cmd: msbuild /t:pack src/Grace.MVC4/Grace.MVC4.csproj /p:Configuration=Release /p:IncludeSymbols=true /p:PackageOutputPath=..\..\
- cmd: msbuild /t:pack src/Grace.MVC5/Grace.MVC5.csproj /p:Configuration=Release /p:IncludeSymbols=true /p:PackageOutputPath=..\..\
artifacts:
- path: Grace*.nupkg
  name: Grace
os: Visual Studio 2017
